blank_issues_enabled: false
contact_links:
  - name: 💬 Discusion / pregunta
    url: https://github.com/dlastra1976/moviendo-leyendas/discussions
    about: Para debatir ideas antes de crear un issue formal.
